



export default {
  token:"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ7XCJ1c2VyXCI6e1wiY2FyZG51bVwiOlwiMDAxXCIsXCJjbGFzc2lmeVwiOjAsXCJjcmVhdGlvbl90aW1lXCI6MTU1MDQ1ODY4MjAwMCxcImRlcHRcIjpcIuacuuaehDFcIixcImlkXCI6OTEsXCJuYW1lXCI6XCIxXCIsXCJvcGVuaWRcIjpcIjFcIixcInBob25lXCI6XCIxNTI2MzIxNTAyXCIsXCJwaWRcIjowLFwic3RhdHVzXCI6MSxcInR5cGVcIjoxfX0iLCJpc3MiOiJ5aXhpbmciLCJleHAiOjE1NTEzNTg1MDF9.UPipuQDdiAgK4k5dFgPzEsxQuQmssnO_X47L08dVQ0E",
  settoken(token) {
    this.token=token;
  },

}
